apiVersion: v1
kind: Pod
metadata:
  name: php-metrics-cpu-test
  namespace: metrics-test
spec:
  containers:
    - name: php-test
      image: php:8.3-cli
      command: ["/bin/sh", "-c"]
      args:
        - |
          cd /workspace
          php -r 'require "vendor/autoload.php";
          $result = PHPeek\SystemMetrics\SystemMetrics::container();
          var_dump($result->getValue());
          sleep(3600);'
      resources:
        requests:
          cpu: "100m"       # 0.1 CPU cores
          memory: "64Mi"
        limits:
          cpu: "500m"       # 0.5 CPU cores
          memory: "256Mi"
      volumeMounts:
        - name: workspace
          mountPath: /workspace
          readOnly: true
  volumes:
    - name: workspace
      hostPath:
        path: /workspace
        type: Directory
  restartPolicy: Never
